export const projects = [
  {
    title: "Al-Jalis As-Salih, Inc. (v2)",
    desc: "Empowering communities through authentic Islamic education.",
    year: "2025",
    made: "Al-Jalis As-Salih, Inc.",
    built: "javascript, laravel, react, tailwindcss, motiondev, mysql, gemini, vscode",
    url: "thegoodcompanion.net",
    href: "https://thegoodcompanion.net",
  },
  {
    title: "Portfolio / Creative Resume",
    desc: "Built with Next.js and Tailwind CSS for showcasing creative resume.",
    year: "2025",
    built: "javascript, nextjs, tailwindcss, vercel, gemini, vscode",
    url: "GitHub Repository",
    href: "https://github.com/mamangcao/portfolio-nextjs",
  },
  {
    title: "The Good Companion Academy",
    desc: "A comprehensive academy providing transformative Islamic education.",
    year: "2024",
    made: "The Good Companion Academy",
    built: "wordpress, typescript, laravel, react, vitejs, tailwindcss, mysql, vscode",
    url: "academy.thegoodcompanion.net",
    href: "https://academy.thegoodcompanion.net",
  },
  {
    title: "Al-Jalis As-Salih, Inc. (v1)",
    desc: "Empowering communities through authentic Islamic education.",
    year: "2019",
    made: "Al-Jalis As-Salih, Inc.",
    built: "laravel, php, materialui, mysql",
    url: "thegoodcompanion.net",
    href: "",
  },
  {
    title: "MIMSA Attendance System",
    desc: "Attendance system for MIMSA using their ID Number as reference.",
    year: "2018",
    built: "laravel, php, bootstrap, postgresql",
    url: "",
    href: "",
  },
  {
    title: "Pharmacy Web Management System",
    desc: "Pharmacy web management system for inventory and sales tracking.",
    year: "2018",
    built: "laravel, php, materialui, postgresql",
    url: "",
    href: "",
  },
];
